In [42]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
Json_Path = '~/Downloads/response.json'

In [3]:
def getJsonDF(dataSetPath: str) ->pd.DataFrame:

    df_json = pd.read_json(dataSetPath)
    
    return df_json

In [75]:
def getSubDaily(df_json: pd.DataFrame) ->list():

    daily_sum = df_json.reservations[:].apply(lambda x: x['dailySummary'])
    sub_daily = [val for sub_daily in daily_sum for val in sub_daily]
    
    return sub_daily
    
def getDF_Daily(df_json: pd.DataFrame) ->pd.DataFrame:
    
    sub_daily = getSubDaily(df_json)
    
    daily_dicts = dict()
    df_dailySum = pd.DataFrame()

    for sub in sub_daily:
        for key, val in zip(sub.keys(), sub.values()):
            daily_dicts[key] = val
            df_daily = pd.DataFrame([daily_dicts])
        df_dailySum = pd.concat([df_dailySum, df_daily])
    
    return df_dailySum.reset_index(drop=True)

def getNumDays(df_json: pd.DataFrame) ->pd.DataFrame():
    
    daily_sum = df_json.reservations[:].apply(lambda x: x['dailySummary'])
    numDays = list()

    for d in daily_sum:
        num_d = len(d)
        numDays.append(num_d)
    
    df_numDays = pd.DataFrame(numDays)
        
    return df_numDays

def getMetaData(df_json: pd.DataFrame) ->pd.DataFrame():

    metadata_dict = dict()
    df_DailyMetaData = pd.DataFrame()

    for r in df_json['reservations']:
        for key, value in zip(r.keys(), r.values()):
            if (key != 'reservationIdList') & (key != 'dailySummary'):
                metadata_dict[key] = value
                df_MetaData = pd.DataFrame([metadata_dict])
        df_DailyMetaData = pd.concat([df_DailyMetaData, df_MetaData])

    return df_DailyMetaData.reset_index(drop=True)

In [253]:
def getReservationIdList(df_json: pd.DataFrame) ->list(): 
    
    reservationId = list()

    for r in df_json['reservations']:
        reservationId.append(r['reservationIdList'])
        
    return reservationId

def getConfirmationId(reservationId: list()) ->pd.DataFrame:
    
    df_confirm = pd.DataFrame(reservationId)
    df_confirm[0] = df_confirm[0].apply(lambda x: int(x['id']))
    df_confirm = df_confirm.drop(columns=[1, 2])
    return df_confirm

def getReservationId(reservationId: list()) ->pd.DataFrame:
    
    df_reservation = pd.DataFrame(reservationId)
    df_reservation[1] = df_reservation[1].apply(lambda x: int(x['id']))
    df_reservation = df_reservation.drop(columns=[0, 2])
    return df_reservation

def getStatusId(df_json: pd.DataFrame) ->pd.DataFrame:
        
    reservationId = getReservationIdList(df_json)    
        
    df_status = pd.DataFrame()
    df_status['confirmationId'] = getConfirmationId(reservationId)
    df_status['reservationId'] = getReservationId(reservationId)
    
    return df_status

def getFullRecord(df_status: pd.DataFrame, 
                  df_DailyMetaData: pd.DataFrame, 
                  df_numDays: pd.DataFrame) ->pd.DataFrame:
    
    df_FullStatus = df_status.merge(df_DailyMetaData, left_index=True, right_index=True)
    df_FullRecord = pd.DataFrame(np.repeat(df_FullStatus.values, df_numDays[0], axis=0))
    
    return df_FullRecord

def getColumns(df_json: pd.DataFrame) ->dict():
    
    
    max_cols = list()
    max_cols.append('confirmationId')
    max_cols.append('reservationId')

    for r in df_json['reservations']:
        
        excluded_col = 2 # Excluded 1. reservationIdList 2. dailySummary
        max_col = len(r)
        included_col = max_col - excluded_col
        
        if max_col - excluded_col == included_col:
            for key in r.keys():
                if (key != 'reservationIdList') & (key != 'dailySummary'):
                    max_cols.append(key)
            break
    
    columns_dict = dict()

    for idx, col in enumerate(max_cols):
        columns_dict[idx] = col
            
    return columns_dict

In [265]:
def cleanDataType(df: pd.DataFrame) ->pd.DataFrame:
    
    df['confirmationId'] = df.confirmationId.astype('int')
    df['reservationId'] = df.reservationId.astype('int')
    df['arrival'] = pd.to_datetime(df.arrival, format='%Y-%m-%d %H:%M:%S')
    df['departure'] = pd.to_datetime(df.departure, format='%Y-%m-%d %H:%M:%S')
    df['bookingDate'] = pd.to_datetime(df.bookingDate, format='%Y-%m-%d %H:%M:%S')
    df['noOfRooms'] = df.noOfRooms.astype('int')
    df['createDateTime'] = pd.to_datetime(df.createDateTime, format='%Y-%m-%d %H:%M:%S')
    df['lastModifiedDateTime'] = pd.to_datetime(df.lastModifiedDateTime, format='%Y-%m-%d %H:%M:%S')
    df['children1'] = df.children1.astype('int')
    df['children2'] = df.children2.astype('int')
    df['children3'] = df.children3.astype('int')
    df[15] = pd.to_datetime(df[15], format='%Y-%m-%d %H:%M:%S') # Find out the column name
    df['rateAmount'] = df.rateAmount.astype('int')
    df['trxDate'] = pd.to_datetime(df.trxDate, format='%Y-%m-%d %H:%M:%S')
    df['adults'] = df.adults.astype('int')
    df['room'] = df.room.fillna(0).astype('int')
    df['roomRevenue'] = df.roomRevenue.fillna(0).astype('int')
    df['totalRevenue'] = df.totalRevenue.fillna(0).astype('int')
    df['tax'] = df.tax.fillna(0).astype('float')
    
    return df

def getReport(df_record: pd.DataFrame, df_daily: pd.DataFrame, columns: dict()) ->pd.DataFrame:
    
    df_FullRecords = df_record.merge(df_daily, left_index=True, right_index=True)
    df_FullRecords = df_FullRecords.rename(columns=columns)
    
    return df_FullRecords

def JSonParser() ->pd.DataFrame:
    
    df_json = getJsonDF(Json_Path)
    columns_dict = getColumns(df_json)
    df_status = getStatusId(df_json)
    df_numDays = getNumDays(df_json)
    df_dailySum = getDF_Daily(df_json)
    df_DailyMetaData = getMetaData(df_json)

    df_FullRecord = getFullRecord(df_status, df_DailyMetaData, df_numDays)
    df_FullRecords = getReport(df_FullRecord, df_dailySum, columns_dict)
    df_FullRecords = cleanDataType(df_FullRecords)
    
    return df_FullRecords

In [266]:
df_FullRecords = JSonParser()
df_FullRecords

,confirmationId,reservationId,resvStatus,sharedYn,arrival,departure,bookingDate,resvType,noOfRooms,createDateTime,...,taxCurrency,roomTypeCharged,trxDate,sourceCode,channel,adults,room,roomRevenue,totalRevenue,tax
0,1126134,82813,NO SHOW,N,2022-10-06,2022-10-08,2022-04-29,6PM,1,2022-04-29 15:50:25,...,USD,ECO,2022-10-06,PHONE,WEB,2,0,0,0,0.00
1,1126403,82932,NO SHOW,N,2022-10-04,2022-10-06,2022-04-29,6PM,1,2022-04-29 15:54:59,...,USD,ECO,2022-10-05,PHONE,WEB,2,0,0,0,0.00
2,1126784,83184,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 16:16:54,...,USD,SGL,2022-10-05,PHONE,WEB,2,106,150,150,16.50
3,1126784,83184,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 16:16:54,...,USD,SGL,2022-10-06,PHONE,WEB,2,106,150,150,16.50
4,1126798,83191,NO SHOW,N,2022-10-04,2022-10-06,2022-04-29,6PM,1,2022-04-29 16:17:30,...,USD,ROYAL,2022-10-05,PHONE,WEB,2,106,150,150,16.50
5,1126941,83261,NO SHOW,N,2022-10-06,2022-10-08,2022-04-29,6PM,1,2022-04-29 18:03:54,...,USD,JSUI,2022-10-06,PHONE,WEB,2,106,150,150,16.50
6,1127642,83680,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 18:02:12,...,USD,ECO,2022-10-05,PHONE,WEB,2,101,225,225,24.75
7,1127642,83680,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 18:02:12,...,USD,ECO,2022-10-06,PHONE,WEB,2,101,225,225,24.75
8,1127645,83682,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 18:02:20,...,USD,DBL,2022-10-05,PHONE,WEB,2,201,175,175,19.25
9,1127645,83682,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 18:02:20,...,USD,DBL,2022-10-06,PHONE,WEB,2,201,175,175,19.25
10,1128536,84026,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 18:17:59,...,USD,ECO,2022-10-05,PHONE,WEB,2,102,225,225,24.75
11,1128536,84026,CHECKED OUT,N,2022-10-05,2022-10-07,2022-04-29,CHECKED IN,1,2022-04-29 18:17:59,...,USD,ECO,2022-10-06,PHONE,WEB,2,102,225,225,24.75
12,1128554,84036,NO SHOW,N,2022-10-06,2022-10-08,2022-04-29,6PM,1,2022-04-29 18:18:23,...,USD,ROYAL,2022-10-06,PHONE,WEB,2,102,225,225,24.75
13,1128719,84126,NO SHOW,N,2022-10-06,2022-10-08,2022-04-29,6PM,1,2022-04-29 18:21:38,...,USD,SUP,2022-10-06,PHONE,WEB,2,102,225,225,24.75

In [267]:
def SaveReport(df: pd.DataFrame, excel: str=None, csv: str=None):
    
    '''
    This function should install "openpyxl" module to use excel writer
    
    Install with the command:
    
    pip install openpyxl or pip3 install openpyxl
    
    Set excel parameter to True in order to save as excel file
    otherwise for csv as well
    '''
    
    savePath = Path(input(f'Please select folder or path to save the report: '))
    savePath.mkdir(parents=True, exist_ok=True)
    
    filename = input(f'Please set your filename to save out: ')
    sheetname = input(f'Please set your sheetname to save out: ')
    
    # One sheet only
    if excel:
        df.to_excel(f"{savePath}/{filename}.xlsx", sheet_name=sheetname)
    elif csv:
        df.to_csv(f"{savePath}/{filename}.csv")
    
    print("Save report is complete...")

In [269]:
SaveReport(df_FullRecords, excel=True)

In [239]:
# map_dict = {
#  'confirmationId': 'Confirmation_no',
#  'reservationId': 'Reservation_no',
#  'resvStatus': 'Status',
#  'sharedYn': '',
#  'arrival': 'Arrival_date',
#  'departure': 'Departure_date',
#  'bookingDate': 'Created_date',
#  'resvType': 'Guarantee',
#  'noOfRooms': 'Room',
#  'createDateTime': 'Created_date',
#  'lastModifiedDateTime': 'Modify_date',
#  'children1': 'Children',
#  'children2': '',
#  'children3': '',
#  'bookingMedium': 'Source',
#  15:'',
#  'rateCode': 'Rate_code',
#  'rateAmount': 'Rate_amount',
#  'marketCode': 'Market_code',
#  'roomType': 'Room_type',
#  'bookedRoomType': '',
#  'roomRevenueCurrency': '',
#  'fbRevenueCurrency': '',
#  'otherRevenueCurrency': '',
#  'totalRevenueCurrency': 'Currency',
#  'packageRevenueCurrency': '',
#  'taxCurrency': '',
#  'roomTypeCharged': 'RTC',
#  'trxDate': 'Business_date',
#  'sourceCode': 'Source_code',
#  'channel': 'Channel',
#  'adults': 'Adult',
#  'room': '',
#  'roomRevenue': 'Room_revenue',
#  'totalRevenue': 'Total_revenue',
#  'tax': ''
# }